datasets:
  raw:
    housing_price:
      type: ds
      format: csv
      uri: ${core.data_base_path}/raw/housing_price/housing.csv
      driver_params: {}


  cleaned:
    housing_price:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/cleaned/housing_price/housing.parquet
      driver_params: {}


  processed:
    housing_price:
      type: ds
      format: parquet
      uri: ${core.data_base_path}/processed/housing_price/housing.parquet
      driver_params: {}

  train:
    housing_price:
      features:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/train/housing_price/features.parquet
        driver_params:
          save:
            index: False
      target:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/train/housing_price/target.parquet
        driver_params:
          save:
            index: False
  test:
    housing_price:
      features:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/test/housing_price/features.parquet
        driver_params:
          save:
            index: False
      target:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/test/housing_price/target.parquet
        driver_params:
          save:
            index: False
  score:
    housing_price:
      output:
        type: ds
        format: parquet
        uri: ${core.data_base_path}/test/housing_price/scored_output.parquet
        driver_params:
          save:
            index: False